name: collect-coverage
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      affectedPackages: ${{ steps.get-affected-packages.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'refs/remotes/origin/master'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            pnpm-store-
        
      - name: Install dependencies
        run: pnpm install

      - name: Get affected packages
        id: get-affected-packages
        run: echo "packages=$(pnpm exec iocuak-get-affected-projects test:unit:js:coverage)" >> $GITHUB_OUTPUT

      - name: Compile source files
        run: pnpm run build:all

      - name: Get current git commit hash
        id: get-git-commit-hash
        run: |
          echo "gitCommitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: ts-build-cache
        with:
          path: |
            ./packages
          key: ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}
          restore-keys: |
            ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}

  test-coverage-package:
    name: Test with coverage
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.affectedPackages != '[]' }}
    strategy:
      matrix:
        package: ${{fromJSON(needs.build.outputs.affectedPackages)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            pnpm-store-
        
      - name: Install dependencies
        run: pnpm install

      - name: Get current git commit hash
        id: get-git-commit-hash
        run: |
          echo "gitCommitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: ts-build-cache
        with:
          path: |
            ./packages
          key: ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}
          restore-keys: |
            ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}

      - name: Build on cache miss
        run: pnpm run build:all --filter ${{ matrix.package }}
        if: ${{ !steps.ts-build-cache.outputs.cache-hit }}

      - name: Launch Unit Tests and generate coverage report
        run: pnpm run test:unit:js:coverage --filter ${{ matrix.package }} --only -- --selectProjects Unit

      - name: Upload coverage to Codecov (branch)
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.package }}
          override_branch: master
          token: ${{ secrets.CODECOV_TOKEN }}

  test-coverage:
    name: Test with coverage
    needs:
      - test-coverage-package
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Done!"'
